# Generated by Django 2.2 on 2023-03-17 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_coins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coins',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coins', to=settings.AUTH_USER_MODEL),
        ),
    ]
