# Generated by Django 2.2 on 2023-03-17 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230317_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upgrades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color', models.BooleanField()),
                ('username_border', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='upgrades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Апгрейды',
            },
        ),
    ]
