# Generated by Django 2.2 on 2023-03-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_upgrades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coins',
            name='value',
            field=models.SmallIntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='upgrades',
            name='background_color',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='upgrades',
            name='username_border',
            field=models.BooleanField(default=False),
        ),
    ]
