# Generated by Django 2.2 on 2023-03-17 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_surveys', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='surveys.Survey', verbose_name='Опрос'),
        ),
        migrations.AddField(
            model_name='completedsurvey',
            name='answers',
            field=models.ManyToManyField(through='surveys.AnswerToQuestion', to='surveys.AnswerOption'),
        ),
        migrations.AddField(
            model_name='completedsurvey',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed', to='surveys.Survey'),
        ),
        migrations.AddField(
            model_name='completedsurvey',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_surveys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answertoquestion',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='surveys.AnswerOption'),
        ),
        migrations.AddField(
            model_name='answertoquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='surveys.Question'),
        ),
        migrations.AddField(
            model_name='answertoquestion',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.CompletedSurvey'),
        ),
        migrations.AddField(
            model_name='answeroption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_options', to='surveys.Question', verbose_name='Вопрос'),
        ),
    ]
