# Generated by Django 2.2 on 2023-03-17 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_auto_20230317_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answertoquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.Question'),
        ),
        migrations.AlterField(
            model_name='answertoquestion',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='surveys.CompletedSurvey'),
        ),
    ]
