# Generated by Django 2.2 on 2023-03-18 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_survey_coins_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_surveys', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
